### PR TITLE
serialize-der

### PR DESCRIPTION
**Pull request by cmayorga**
Added wrapper and example for native secp256k1_ecdsa_signature_serialize_der

### CODE REVIEW

**Comment by zone117x** [comment]
Can you add this to the unit tests? Other than that, this looka good, thank you!

**Comment by cmayorga** [comment]
> Can you add this to the unit tests? Other than that, this looka good, thank you!

Thank you for your .NET library. Very useful to my new blockchain SDK. ;)

**Comment by zone117x** [comment]
Looks great, thanks!
@Xenomega merging this in -- let me know if you see any problems and we can address

**Comment by cmayorga** [comment]
> Looks great, thanks!
> @Xenomega merging this in -- let me know if you see any problems and we can address

Hi, Could you update the nuget package please? it seems not to be updated ...

**Comment by zone117x** [comment]
Hey @cmayorga, apologies for the delay, this github notification feel through the cracks. 
These changes are published in latest package https://www.nuget.org/packages/Secp256k1.Net/0.1.55

**Pull request merged**
